function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

if(size(im,3)==3)
    % Convert RGB to grayscale
    imgray = rgb2gray(im);
else
    imgray = im;
end

bw = imbinarize(imgray);

src1 = im2uint8(im);
pos = [79.9612005856517,493.759150805271,1931.05710102489,1037.49341142021];
imCp1 = imcrop(src1,pos);

results.imCp1 = imCp1;


results.imgray = imgray;
results.bw     = bw;

%--------------------------------------------------------------------------
