function results = myimfcn(im)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------

if(size(im,3)==3)
    % Convert RGB to grayscale
    imgray = rgb2gray(im);
else
    imgray = im;
end

bw = imbinarize(imgray);

src1 = im2uint8(im);
pos = [541.735724743778 574.719619326501 908.556368960468 809.604685212298];
imCp = imcrop(src1,pos);

results.imCp = imCp;


results.imgray = imgray;
results.bw     = bw;

%--------------------------------------------------------------------------
